#!/bin/bash
javac *.java -d test
cd test
java Driver 1 0 >> ../out1.csv
java Driver 1 0 >> ../out1.csv
java Driver 1 0 >> ../out1.csv
java Driver 1 0 >> ../out1.csv
java Driver 1 0 >> ../out1.csv
java Driver 1 0 >> ../out1.csv
java Driver 1 0 >> ../out1.csv
java Driver 1 0 >> ../out1.csv
java Driver 1 0 >> ../out1.csv
java Driver 1 0 >> ../out1.csv
java Driver 1 0 >> ../out1.csv
java Driver 1 0 >> ../out1.csv
java Driver 1 0 >> ../out1.csv
java Driver 1 0 >> ../out1.csv
java Driver 1 0 >> ../out1.csv
java Driver 1 0 >> ../out1.csv
java Driver 1 0 >> ../out1.csv
java Driver 1 0 >> ../out1.csv
java Driver 1 0 >> ../out1.csv
java Driver 1 0 >> ../out1.csv
java Driver 1 0 >> ../out1.csv
java Driver 1 0 >> ../out1.csv
java Driver 1 0 >> ../out1.csv
java Driver 1 0 >> ../out1.csv
java Driver 1 0 >> ../out1.csv
java Driver 1 0 >> ../out1.csv
java Driver 1 0 >> ../out1.csv
java Driver 1 0 >> ../out1.csv
java Driver 1 0 >> ../out1.csv
java Driver 1 0 >> ../out1.csv
java Driver 1 0 >> ../out1.csv
java Driver 1 0 >> ../out1.csv
java Driver 1 0 >> ../out1.csv
java Driver 1 0 >> ../out1.csv
java Driver 1 0 >> ../out1.csv
java Driver 1 0 >> ../out1.csv
java Driver 1 0 >> ../out1.csv
java Driver 1 0 >> ../out1.csv
java Driver 1 0 >> ../out1.csv
java Driver 1 0 >> ../out1.csv
java Driver 1 0 >> ../out1.csv
java Driver 1 0 >> ../out1.csv
java Driver 1 0 >> ../out1.csv
java Driver 1 0 >> ../out1.csv
java Driver 1 0 >> ../out1.csv
java Driver 1 0 >> ../out1.csv
java Driver 1 0 >> ../out1.csv
java Driver 1 0 >> ../out1.csv
java Driver 1 0 >> ../out1.csv
java Driver 1 0 >> ../out1.csv
java Driver 2 0 >> ../out2.csv
java Driver 2 0 >> ../out2.csv
java Driver 2 0 >> ../out2.csv
java Driver 2 0 >> ../out2.csv
java Driver 2 0 >> ../out2.csv
java Driver 2 0 >> ../out2.csv
java Driver 2 0 >> ../out2.csv
java Driver 2 0 >> ../out2.csv
java Driver 2 0 >> ../out2.csv
java Driver 2 0 >> ../out2.csv
java Driver 2 0 >> ../out2.csv
java Driver 2 0 >> ../out2.csv
java Driver 2 0 >> ../out2.csv
java Driver 2 0 >> ../out2.csv
java Driver 2 0 >> ../out2.csv
java Driver 2 0 >> ../out2.csv
java Driver 2 0 >> ../out2.csv
java Driver 2 0 >> ../out2.csv
java Driver 2 0 >> ../out2.csv
java Driver 2 0 >> ../out2.csv
java Driver 2 0 >> ../out2.csv
java Driver 2 0 >> ../out2.csv
java Driver 2 0 >> ../out2.csv
java Driver 2 0 >> ../out2.csv
java Driver 2 0 >> ../out2.csv
java Driver 2 0 >> ../out2.csv
java Driver 2 0 >> ../out2.csv
java Driver 2 0 >> ../out2.csv
java Driver 2 0 >> ../out2.csv
java Driver 2 0 >> ../out2.csv
java Driver 2 0 >> ../out2.csv
java Driver 2 0 >> ../out2.csv
java Driver 2 0 >> ../out2.csv
java Driver 2 0 >> ../out2.csv
java Driver 2 0 >> ../out2.csv
java Driver 2 0 >> ../out2.csv
java Driver 2 0 >> ../out2.csv
java Driver 2 0 >> ../out2.csv
java Driver 2 0 >> ../out2.csv
java Driver 2 0 >> ../out2.csv
java Driver 2 0 >> ../out2.csv
java Driver 2 0 >> ../out2.csv
java Driver 2 0 >> ../out2.csv
java Driver 2 0 >> ../out2.csv
java Driver 2 0 >> ../out2.csv
java Driver 2 0 >> ../out2.csv
java Driver 2 0 >> ../out2.csv
java Driver 2 0 >> ../out2.csv
java Driver 2 0 >> ../out2.csv
cd ..
